export const courseProduct = [
  // Web Development
  {
    category: "Web Development",
    title: "Build Website with HTML",
    description:
      "Far advanced settling say finished raillery. Offered chiefly farther",
    level: "basicLevel",
    heart: "solid",
    imgSrc: "../img/web1.jpg",
    rating: "5.0/5.0",
    time: "45 hours",
    lectures: "10 lectures",
  },
  {
    category: "Web Development",
    title: "Build Websites with CSS",
    description:
      "Far advanced settling say finished raillery. Offered chiefly farther",
    level: "mediumLevel",
    heart: "regular",
    imgSrc: "../img/web2.jpg",
    rating: "4.5/5.0",
    time: "45 hours",
    lectures: "12 lectures",
  },
  {
    category: "Web Development",
    title: "JavaScript: Understanding",
    description:
      "Far advanced settling say finished raillery. Offered chiefly farther",
    level: "advancedLevel",
    heart: "solid",
    imgSrc: "../img/web3.jpg",
    rating: "5.0/5.0",
    time: "60 hours",
    lectures: "20 lectures",
  },
  {
    category: "Web Development",
    title: "Bootstrap 5 From Scratch",
    description:
      "Far advanced settling say finished raillery. Offered chiefly farther",
    level: "basicLevel",
    heart: "regular",
    imgSrc: "../img/web4.jpg",
    rating: "4.0/5.0",
    time: "40 hours",
    lectures: "10 lectures",
  },
  {
    category: "Web Development",
    title: "Tailwind CSS framework",
    description:
      "Far advanced settling say finished raillery. Offered chiefly farther",
    level: "basicLevel",
    heart: "regular",
    imgSrc: "../img/web5.jpg",
    rating: "4.0/5.0",
    time: "40 hours",
    lectures: "10 lectures",
  },
  {
    category: "Web Development",
    title: "React Js is the library",
    description:
      "Far advanced settling say finished raillery. Offered chiefly farther",
    level: "mediumLevel",
    heart: "solid",
    imgSrc: "../img/web6.jpg",
    rating: "4.0/5.0",
    time: "70 hours",
    lectures: "25 lectures",
  },
  {
    category: "Web Development",
    title: "Next Js The React library",
    description:
      "Far advanced settling say finished raillery. Offered chiefly farther",
    level: "mediumLevel",
    heart: "regular",
    imgSrc: "../img/web7.jpg",
    rating: "4.0/5.0",
    time: "60 hours",
    lectures: "30 lectures",
  },
  {
    category: "Web Development",
    title: "Angular - Complete Guider",
    description:
      "Far advanced settling say finished raillery. Offered chiefly farther",
    level: "mediumLevel",
    heart: "regular",
    imgSrc: "../img/web8.jpg",
    rating: "4.0/5.0",
    time: "50 hours",
    lectures: "25 lectures",
  },

  // Mobile App Development
  {
    category: "Mobile Devolopment",
    title: "Flutter Mobile App ",
    description:
      "Far advanced settling say finished raillery. Offered chiefly farther",
    level: "advancedLevel",
    heart: "solid",
    imgSrc: "../img/app1.jpg",
    rating: "5.0/5.0",
    time: "70 hours",
    lectures: "30 lectures",
  },
  {
    category: "Mobile Devolopment",
    title: "Learning with React-Native",
    description:
      "Far advanced settling say finished raillery. Offered chiefly farther",
    level: "mediumLevel",
    heart: "regular",
    imgSrc: "../img/app2.jpg",
    rating: "4.5/5.0",
    time: "80 hours",
    lectures: "30 lectures",
  },
  {
    category: "Mobile Devolopment",
    title: "Swift is  Objective-C",
    description:
      "Far advanced settling say finished raillery. Offered chiefly farther",
    level: "advancedLevel",
    heart: "regular",
    imgSrc: "../img/app3.jpg",
    rating: "4.0/5.0",
    time: "80 hours",
    lectures: "40 lectures",
  },
  {
    category: "Mobile Devolopment",
    title: "Kotlin Programming",
    description:
      "Far advanced settling say finished raillery. Offered chiefly farther",
    level: "advancedLevel",
    heart: "regular",
    imgSrc: "../img/app4.jpg",
    rating: "4.0/5.0",
    time: "70 hours",
    lectures: "35 lectures",
  },
  // programming Languages
  {
    category: "Programming Language",
    title: "C++ Programming",
    description:
      "Far advanced settling say finished raillery. Offered chiefly farther",
    level: "basicLevel",
    heart: "regular",
    imgSrc: "../img/programming1.jpg",
    rating: "4.0/5.0",
    time: "70 hours",
    lectures: "40 lectures",
  },
  {
    category: "Programming Language",
    title: "Java Programming",
    description:
      "Far advanced settling say finished raillery. Offered chiefly farther",
    level: "basicLevel",
    heart: "regular",
    imgSrc: "../img/programming2.jpg",
    rating: "4.0/5.0",
    time: "90 hours",
    lectures: "50 lectures",
  },
  {
    category: "Programming Language",
    title: "Python Programming",
    description:
      "Far advanced settling say finished raillery. Offered chiefly farther",
    level: "advancedLevel",
    heart: "regular",
    imgSrc: "../img/programming3.jpg",
    rating: "4.0/5.0",
    time: "80 hours",
    lectures: "30 lectures",
  },
  {
    category: "Programming Language",
    title: "Spring Frameworks",
    description:
      "Far advanced settling say finished raillery. Offered chiefly farther",
    level: "advancedLevel",
    heart: "regular",
    imgSrc: "../img/programming4.jpg",
    rating: "4.0/5.0",
    time: "100 hours",
    lectures: "55 lectures",
  },
  {
    category: "Programming Language",
    title: "PHP With - CMS Project",
    description:
      "Far advanced settling say finished raillery. Offered chiefly farther",
    level: "mediumLevel",
    heart: "regular",
    imgSrc: "../img/programming5.jpg",
    rating: "4.0/5.0",
    time: "60 hours",
    lectures: "30 lectures",
  },
  {
    category: "Programming Language",
    title: "C# Programming",
    description:
      "Far advanced settling say finished raillery. Offered chiefly farther",
    level: "basicLevel",
    heart: "regular",
    imgSrc: "../img/programming6.jpg",
    rating: "4.0/5.0",
    time: "80 hours",
    lectures: "30 lectures",
  },

  // Database
  {
    category: "Database",
    title: "MySQL Sever",
    description:
      "Far advanced settling say finished raillery. Offered chiefly farther",
    level: "mediumLevel",
    heart: "regular",
    imgSrc: "../img/db1.jpg",
    rating: "4.0/5.0",
    time: "60 hours",
    lectures: "30 lectures",
  },
  {
    category: "Database",
    title: "PostgreSQL",
    description:
      "Far advanced settling say finished raillery. Offered chiefly farther",
    level: "mediumLevel",
    heart: "regular",
    imgSrc: "../img/db2.jpg",
    rating: "4.0/5.0",
    time: "50 hours",
    lectures: "20 lectures",
  },
  {
    category: "Database",
    title: "MongoDB Atlas integrates",
    description:
      "Far advanced settling say finished raillery. Offered chiefly farther",
    level: "basicLevel",
    heart: "regular",
    imgSrc: "../img/db3.jpg",
    rating: "4.0/5.0",
    time: "60 hours",
    lectures: "30 lectures",
  },
  // Graphic Design
  {
    category: "Graphic Design",
    title: "adobe illustrator",
    description:
      "Far advanced settling say finished raillery. Offered chiefly farther",
    level: "basicLevel",
    heart: "regular",
    imgSrc: "../img/design1.jpg",
    rating: "4.0/5.0",
    time: "60 hours",
    lectures: "30 lectures",
  },
  {
    category: "Graphic Design",
    title: "Photoshop  Masterclass",
    description:
      "Far advanced settling say finished raillery. Offered chiefly farther",
    level: "basicLevel",
    heart: "regular",
    imgSrc: "../img/design2.jpg",
    rating: "4.0/5.0",
    time: "60 hours",
    lectures: "30 lectures",
  },
  {
    category: "Graphic Design",
    title: "Design System in Figma",
    description:
      "Far advanced settling say finished raillery. Offered chiefly farther",
    level: "basicLevel",
    heart: "regular",
    imgSrc: "../img/design3.jpg",
    rating: "4.0/5.0",
    time: "60 hours",
    lectures: "30 lectures",
  },
];
